version: '3.8'
services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - '${PGPORT}:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local